// frontend/src/components/conversation/index.tsx
import { useStore } from '../../store/useStore';
import { EmptyState } from './shared';
import { PMView } from './PMView';
import { RoomView } from './RoomView';


export function Conversation() {
  const active = useStore((s) => s.active);
  if (!active) return <EmptyState />;
  if (active.kind === 'pm') return <PMView key={`pm:${active.id}`} peerId={active.id} />;
  return <RoomView key={`room:${active.id}`} roomId={active.id} />;
}

/* ----------------------------------------------------------------------- */

// frontend/src/components/conversation/Conversation.vue
<script setup lang="ts">
import { useStore } from '../../store/useStore';
import EmptyState from './EmptyState.vue';
import PMView from './PMView.vue';
import RoomView from './RoomView.vue';

const st = useStore();
</script>

<template>
  <EmptyState v-if="!st.active" />
  <PMView v-else-if="st.active.kind === 'pm'" :key="`pm:${st.active.id}`" :peerId="st.active.id" />
  <RoomView v-else :key="`room:${st.active.id}`" :roomId="st.active.id" />
</template>
